name: Cypress Tests

on:
  push:
    branches:
      - main # Repository's default branch

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Go to project folder
      run: cd 03-react-auth

    - name: Install dependencies
      run: npm install
      working-directory: ./03-react-auth

    - name: Run Cypress tests
      run: npm run cypress:run
      working-directory: ./03-react-auth
